#!/usr/bin/env bash

echo "Brew updates..."
brew upgrade
brew cask upgrade
brew cleanup -s

echo "NPM updates..."
npm update -g

# echo "PIP updates..."
# pip2 list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 sudo pip2 install -U
