export ZSH=/Users/remi/.oh-my-zsh
export ZSH_THEME=agnoster
export ENABLE_CORRECTION=true
export HISTFILE=~/.config/zsh/histfile
export HISTSIZE=1000
export SAVEHIST=1000
export ZDOTDIR=~/.config/zsh

plugins=(
	git
)

source $ZSH/oh-my-zsh.sh

export ZSH_CACHE_DIR=~/.config/zsh

if [[ -n $SSH_CONNECTION ]]; then
    export EDITOR=vim
else
    export EDITOR=nvim
fi

export SSH_KEY_PATH=~/.ssh/rsa_id
export GOROOT=/usr/local/opt/go/libexec
export GOPATH=~/Documents/Go
export PATH="$GOROOT/bin:$PATH"
export PATH="$GOPATH/bin:$PATH"
export BABEL_DISABLE_CACHE=1
export NODE_REPL_HISTORY=''
export PACKER_CACHE_DIR=~/.config/packer
export VAGRANT_HOME=~/.config/vagrant
export CHECKPOINT_DISABLE=1
export DEFAULT_USER=$(whoami)

alias vi=$EDITOR
alias vim=$EDITOR
alias nano=$EDITOR
