export ZSH=~/.config/oh-my-zsh
export ZSH_THEME=agnoster
export ENABLE_CORRECTION=false
export HISTFILE=~/.config/zsh/histfile
export HISTSIZE=1000
export SAVEHIST=1000
export ZDOTDIR=~
export ZSH_CACHE_DIR=~/.config/zsh

plugins=(
    git
    docker
    mvn
    npm
    python
)

export ZSH_COMPDUMP="$ZSH_CACHE_DIR/zcompdump"
source "$ZSH/oh-my-zsh.sh"

export KUBECONFIG=~/.kube/config
export HELM_HOME=~/.config/helm

source <(pip3 completion --zsh)
source <(helm completion zsh)
source <(kubectl completion zsh)
source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc'

if [[ -n $SSH_CONNECTION ]]; then
    export EDITOR=vim
else
    export EDITOR=nvim
fi

export SSH_KEY_PATH=~/.ssh/id_rsa
export GOROOT=/usr/local/opt/go/libexec
export GOPATH=~/Documents/Go
export PATH="$GOROOT/bin:$PATH"
export PATH="$GOPATH/bin:$PATH"
export PATH="/usr/local/opt/grep/libexec/gnubin:$PATH"
export PATH="/usr/local/opt/unzip/bin:$PATH"
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
export PATH="/usr/local/opt/llvm/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/llvm/lib"
export CPPFLAGS="-I/usr/local/opt/llvm/include"
export BABEL_DISABLE_CACHE=1
export NODE_REPL_HISTORY=''
export PACKER_CACHE_DIR=~/.config/packer
export VAGRANT_HOME=~/.config/vagrant
export CHECKPOINT_DISABLE=1
export DEFAULT_USER=$(whoami)
export PYLINTHOME=~/.config/pylint
export PATH="$HOME/.config/scripts:$PATH"
export XDG_DATA_HOME=~/.config
export HTTPIE_CONFIG_DIR=~/.config/httpie

alias vi=$EDITOR
alias vim=$EDITOR
alias python=python3
alias pip=pip3
