plugins=(
    git
    docker
    mvn
    npm
    python
    dotenv
)

export ZSH=~/.config/oh-my-zsh
export ZSH_THEME=agnoster
export ENABLE_CORRECTION=false

source "$ZSH/oh-my-zsh.sh"

if [ -f "$CARGO_HOME/env" ]; then
    source "$CARGO_HOME/env"
fi

source <(kubectl completion zsh)

if [[ -n $SSH_CONNECTION ]]; then
    export EDITOR=vim
else
    export EDITOR=nvim
fi

export SSH_KEY_PATH=~/.ssh/id_rsa
export GOROOT=/usr/local/opt/go/libexec
export GOPATH=~/Documents/Go
export PATH="$GOROOT/bin:$PATH"
export PATH="$GOPATH/bin:$PATH"
export PATH="/usr/local/opt/unzip/bin:$PATH"
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
export PATH="/usr/local/opt/curl/bin:$PATH"
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
export PATH="/usr/local/opt/make/libexec/gnubin:$PATH"
export PATH="/usr/local/opt/openssl/bin:$PATH"
export PATH="/usr/local/opt/sqlite/bin:$PATH"
export MANPATH="/usr/local/opt/make/libexec/gnuman:$MANPATH"
export CHECKPOINT_DISABLE=1
export DEFAULT_USER=$(whoami)
export PATH="$HOME/.config/scripts:$PATH"
export GO111MODULE=auto
export ANSIBLE_PYTHON_INTERPRETER=/usr/bin/python3
export PATH="$PATH:~/Library/Android/sdk/platform-tools:~/Library/Android/sdk/tools"
export PATH="$HOME/.fastlane/bin:$PATH"
export NVM_DIR="$HOME/.nvm"

[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"

alias vi=$EDITOR
alias vim=$EDITOR

eval "$(rbenv init -)"
